version: "3.8"
services:
  doodlebug:
    container_name: doodlebug
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      bash -c "
               cd /app &&
               pip install -r requirements_dev.txt &&

               uvicorn doodlebug.main:app --reload --host 0.0.0.0"
